#!/usr/bin/env bash
# Re-run the whole analysis chain, in dependency order, and report each step's exit status.
#
#   ./rerun_downstream.sh
#
# Anything that changes the in-domain set, a family constant, the global fit or the calculation
# rules needs ALL of this, in THIS order.
#
# ORDER MATTERS, AND GETTING IT WRONG IS SILENT. compute_conformal_indomain.py writes the interval
# bands that make_paper_predictions.py and compute_conditional.py read. An earlier version of this
# script ran it after them, so every prediction table carried the PREVIOUS run's intervals: the
# predicted values were right and the lo50/hi50/lo90/hi90 columns were stale, with nothing raising an
# error. The bands in turn read family_calibration.json, so the order is fixed as:
#     family calibration -> reference audit -> deployed route -> interval bands -> predictions
#     -> everything that reads the predictions -> figures -> numbers registry -> release
# RELEASE COPY, generated by make_release.py from the working copy's rerun_downstream.sh.
# Paths mapped to analysis/ corpus/ checks/ paper/; 8 step(s) commented out (reason on
# each line). Run from the repository root:  PY=python bash rerun_downstream.sh
set -u
cd "$(dirname "$0")" || exit 1
PY=${PY:-python}   # release: any interpreter with the requirements installed
export PYTHONIOENCODING=utf-8

# THE BLIND-TEST SEEDS COME FIRST. Until 2026-10-04 this chain started at family_calibration.py and
# never regenerated the five seed files the headline is computed from, so they stayed frozen at
# 2026-09-06 while the training set changed under them (rerun on identical code: 34.7% vs the stored
# 37.2%). Seed 0 is written twice because compute_seed_averaged.py reads it from target_blind_test.csv
# and compute_nested_across_seeds.py from paper/evidence; the run is deterministic.
#
# THE OUT-OF-CHAIN PRODUCERS (FIXPASS C1, 2026-10-05). Every script whose output the paper or the
# registry quotes is now a step. Until then the structure-only / surrogate / calibrated-new / Bi-Pt
# tables, the generator validation, the twin and shared-constant tests, the inter-lab ceiling and the
# model comparison were run by hand and went stale silently: on 2026-10-05 every structure-only,
# surrogate, series-gap and Bi-Pt product still carried the withdrawn shared constant c=0.51, p=0.80
# (make_paper_numbers now refuses to write the registry when that happens). Their order:
#   build_cluster_support       training pool only; FIRST, because compute_nested_across_seeds and
#                               extend_blind_test read cluster_support_real.csv
#   validate_bte_generator      -> bte_generator_validation.csv (read by twins, structure-only, Bi-Pt)
#   test_chemical_twins         -> chemical_twins.csv (Bi-Pt twin ratio, registry)
#   test_shared_constant        -> shared_constant_test.json (labels of the 12 and Bi-Pt tables)
#   test_family_form_nested     -> family_form_nested.json
#   predict_bipt_theory
#   compute_interlab_ceiling, compute_semiempirical_vs_bte, compare_models_production -> fig07_model
# They need family_calibration.json and the shared constant, so they follow compute_conformal_indomain.
# Inputs NOT regenerated here (upstream, rerun by hand when their own inputs change):
#   the optimade_*.json structure caches.
STEPS=(
  analysis/build_cluster_support.py
  "analysis/run_target_blind_test.py --seed 0"
  "analysis/run_target_blind_test.py --seed 0 --out paper/evidence/blind_d2_s0.csv"
  "analysis/run_target_blind_test.py --seed 1 --out paper/evidence/blind_d2_s1.csv"
  "analysis/run_target_blind_test.py --seed 2 --out paper/evidence/blind_d2_s2.csv"
  "analysis/run_target_blind_test.py --seed 3 --out paper/evidence/blind_d2_s3.csv"
  "analysis/run_target_blind_test.py --seed 4 --out paper/evidence/blind_d2_s4.csv"
  analysis/family_calibration.py
  analysis/audit_reference_changes.py
  analysis/compute_deployed_route.py
  analysis/test_range_gate.py
  analysis/compute_conformal_indomain.py
  analysis/validate_bte_generator.py
  analysis/test_chemical_twins.py
  analysis/test_shared_constant.py
  analysis/test_family_form_nested.py
  # (omitted step 1: depends on inputs not redistributed with this archive; its output ships as a fixed table)
  # (omitted step 2: depends on inputs not redistributed with this archive; its output ships as a fixed table)
  # (omitted step 3: depends on inputs not redistributed with this archive; its output ships as a fixed table)
  # (omitted step 4: depends on inputs not redistributed with this archive; its output ships as a fixed table)
  # (omitted step 5: depends on inputs not redistributed with this archive; its output ships as a fixed table)
  # (omitted step 6: depends on inputs not redistributed with this archive; its output ships as a fixed table)
  # (omitted step 7: depends on inputs not redistributed with this archive; its output ships as a fixed table)
  analysis/predict_bipt_theory.py
  analysis/compute_interlab_ceiling.py
  analysis/compute_semiempirical_vs_bte.py
  analysis/compare_models_production.py
  paper/fig11_shap.py
  paper/fig12_dataset.py
  paper/fig13_parity_models.py
  paper/fig14_feature_corr.py
  analysis/make_paper_predictions.py
  analysis/compute_conditional.py
  analysis/compute_seed_averaged.py
  analysis/compute_nested_across_seeds.py
  analysis/compute_null_baselines.py
  analysis/compute_domain_headline.py
  analysis/compute_results_indomain.py
  analysis/compute_baselines_ablation.py
  analysis/compute_cap_test.py
  analysis/test_4f_split.py
  analysis/compute_vs_published_model.py
  analysis/compute_family_null.py
  analysis/compute_prediction_funnel.py
  paper/fig01_corpus.py
  paper/fig02_offset.py
  paper/fig03_curves.py
  paper/fig04_blind.py
  paper/fig05_predictions.py
  paper/fig06_landscape.py
  paper/fig08_method.py
  paper/fig09_family.py
  analysis/compute_shared_constant_stability.py
  analysis/make_paper_numbers.py
  paper/fig10_ml.py
  paper/fig15_model_blind.py     # reads the registry (ml_generator_validation, shap_ranking, in_domain_table)
  paper/fig_graphical_abstract.py
  # build_release_data.py   # NOT IN RELEASE: working-copy tool, not part of the release
)
# Optional slice for runs longer than one sitting: FROM=<first step> TO=<last step>, 0-based and
# inclusive (e.g. FROM=0 TO=27 ./rerun_downstream.sh, then FROM=28 ./rerun_downstream.sh). The order
# is still the dependency order above; a slice never skips a step it depends on.
FROM=${FROM:-0}
TO=${TO:-$(( ${#STEPS[@]} - 1 ))}
STEPS=("${STEPS[@]:$FROM:$(( TO - FROM + 1 ))}")
fail=0
for s in "${STEPS[@]}"; do
  t0=$(date +%s)
  # a step may carry arguments; the log name is the step text, flattened
  log="/tmp/rerun_$(echo "$s" | tr ' /' '__').log"
  # shellcheck disable=SC2086
  "$PY" $s > "$log" 2>&1
  rc=$?
  t1=$(date +%s)
  printf "%-36s exit=%d  %4ds\n" "$s" "$rc" "$((t1 - t0))"
  [ "$rc" -ne 0 ] && fail=$((fail + 1)) && tail -5 "$log" | sed 's/^/      /'
done
echo "failures: $fail"
